#!/bin/bash

set -euo pipefail

cd "$(dirname "$0")"

echo "begin execute.sh --------------------------------------------------------"
echo "CS_PYTHON ${CS_PYTHON}"
echo "which ${CS_PYTHON} $(which "${CS_PYTHON}")"
echo "WSE_GOL_EXECUTE_FLAGS ${WSE_GOL_EXECUTE_FLAGS:-}"

echo "setup LOCAL -------------------------------------------------------------"
echo "LOCAL ${LOCAL:-}"
export MYLOCAL="${LOCAL:-local}/bio240020p/$(uuidgen)"
echo "MYLOCAL ${MYLOCAL}"
mkdir -p "${MYLOCAL}"
touch "${MYLOCAL}/.touch"
cp -r "../cerebraslib" "${MYLOCAL}/cerebraslib"

export WSE_GOL_LOCAL_PATH=${WSE_GOL_LOCAL_PATH:-"/local"}
echo "WSE_GOL_LOCAL_PATH ${WSE_GOL_LOCAL_PATH}"
export WSE_GOL_CEREBRASLIB_PATH=${WSE_GOL_CEREBRASLIB_PATH:-"/cerebraslib"}
echo "WSE_GOL_CEREBRASLIB_PATH ${WSE_GOL_CEREBRASLIB_PATH}"

echo "configure container ENV -------------------------------------------------"
export APPTAINERENV_WSE_GOL_LOCAL_PATH="${WSE_GOL_LOCAL_PATH}"
echo "APPTAINERENV_WSE_GOL_LOCAL_PATH ${APPTAINERENV_WSE_GOL_LOCAL_PATH}"
export APPTAINERENV_WSE_GOL_CEREBRASLIB_PATH="${WSE_GOL_CEREBRASLIB_PATH}"
echo "APPTAINERENV_WSE_GOL_CEREBRASLIB_PATH ${APPTAINERENV_WSE_GOL_CEREBRASLIB_PATH}"
export APPTAINERENV_WSE_GOL_NCOL="${WSE_GOL_NCOL:-4}"
echo "APPTAINERENV_WSE_GOL_NCOL ${APPTAINERENV_WSE_GOL_NCOL}"
export APPTAINERENV_WSE_GOL_NROW="${WSE_GOL_NROW:-4}"
echo "APPTAINERENV_WSE_GOL_NROW ${APPTAINERENV_WSE_GOL_NROW}"
export APPTAINER_BINDPATH="${MYLOCAL}:/local:rw,../cerebraslib:/cerebraslib:rw"
echo "APPTAINER_BINDPATH ${APPTAINER_BINDPATH}"

export SINGULARITYENV_WSE_GOL_LOCAL_PATH="${APPTAINERENV_WSE_GOL_LOCAL_PATH}"
echo "SINGULARITYENV_WSE_GOL_LOCAL_PATH ${SINGULARITYENV_WSE_GOL_LOCAL_PATH}"
export SINGULARITYENV_WSE_GOL_CEREBRASLIB_PATH="${APPTAINERENV_WSE_GOL_CEREBRASLIB_PATH}"
echo "SINGULARITYENV_WSE_GOL_CEREBRASLIB_PATH ${SINGULARITYENV_WSE_GOL_CEREBRASLIB_PATH}"
export SINGULARITYENV_WSE_GOL_NCOL="${APPTAINERENV_WSE_GOL_NCOL}"
echo "SINGULARITYENV_WSE_GOL_NCOL ${SINGULARITYENV_WSE_GOL_NCOL}"
export SINGULARITYENV_WSE_GOL_NROW="${APPTAINERENV_WSE_GOL_NROW}"
echo "SINGULARITYENV_WSE_GOL_NROW ${SINGULARITYENV_WSE_GOL_NROW}"
export SINGULARITY_BINDPATH="${APPTAINER_BINDPATH}"
echo "SINGULARITY_BINDPATH ${SINGULARITY_BINDPATH}"

echo "run client.py -----------------------------------------------------------"
"${CS_PYTHON}" client.py ${WSE_GOL_EXECUTE_FLAGS:-}
